#!/usr/bin/env bash
# This script configures the local DNS resolution on an Ubuntu server

# Update /etc/hosts to change localhost IP
sudo sed -i 's/127.0.0.1/127.0.0.2/g' /etc/hosts

# Update /etc/resolv.conf to change DNS for facebook.com
sudo sed -i 's/nameserver.*/nameserver 8.8.8.8/g' /etc/resolv.conf
